server:
  port: 8480
  tomcat:
    max-threads: 100   #tomcat最大并发修改为10，默认值为200

spring:
  profiles:
    active: dev   #使用dev的环境配置
  application:
    name: service-cms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_cms?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务器地址
    sentinel:
      transport:
        port: 8081 #与控制台交流的端口， 任意一个未使用的端口都可以
        dashboard: localhost:8080 # 制定控制台服务地址
  redis:
    host: 192.168.18.129
    port: 6379
    database: 0
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数，负值表示无限制 默认=8
        max-wait: -1 #最大阻塞等待时间，负值表示无限制 默认=-1
        max-idle: 8 #最大空闲连接数，默认=8
        min-idle: 0 #最小空闲连接数，默认=8
#service-oss:
#    ribbon:
#      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/windvalley/guli/service/cms/mapper/xml/*.xml
ribbon:
  MaxAutoRetries: 0 #同一实例最大重试次数,不包括首次调用，默认为0
  MaxAutoRetriesNextServer: 1 #其他实例最大重试次数,不包括首次所选择的server，默认为1
  OkToRetryOnAllOperations: false # 如果使用的是get方法，此值不管是否设置，都会执行一次重试，如果设置为post方法，则不会重试
  ConnectTimeout: 5000 #连接建立的超时时长，默认1秒
  ReadTimeout: 5000 #处理请求的超时时长，默认1秒
feign:
  sentinel:
    enabled: true